repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: bump-version
        name: Bump version
        entry: bash bump_version.sh
        language: system
        always_run: true
        pass_filenames: false