app = 'lonchera'
primary_region = 'sjc'

[build]

[env]
DB_PATH = '/data/lonchera.db'

[[mounts]]
source = 'lonchera_data'
destination = '/data'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
